### ISSUE TITLE
判题端  出现错误 unrecognized status code:404

### ISSUE THREAD

**Issue by 18767752565** [massimodong/wzoj#10]
你好，我是之前只用您这个系统的，Copyright 2016 wzoj project UNKNOWN
最近出错，判题端运行wzoj_judger --debug
出现错误 unrecognized status code:404是为什么呢？
判题程序重新编译了 没有出现错误   也不行

**Comment by massimodong** [comment]
你好，能否告诉我是哪个请求返回404了？

**Comment by 18767752565** [comment]
就是判题机的判题状态错线错误
-oj:~$ sudo wzoj_judger --debug
running in debug mode!
home:/home/judger
init configure
OJ_URL:localhost/
OJ_TOKEN:token13
OJ_SLEEPTIME:10
OJ_MAXRUNNING:1

get url:localhost//judger/pending-solutions?judger_token=token13
unrecognized status code:404
unrecognized status code:404

**Comment by massimodong** [comment]
请问网站运行正常吗？
评测机是否和网站在同一台机器上，并且评测机访问
localhost//judger/pending-solutions?judger_token=token13
这个地址的确是在访问oj网站？

**Comment by 18767752565** [comment]
网站运行正常，测评机和网站是在同一台机器
题目的测评状态都是“正在编译”，可能服务器的编译环境也有问题，但是服务器进行编译c++程序是没有问题的
localhost//judger/pending-solutions?judger_token=token13这个是对的 ，在后台也是添加了token13
本地地址是192.168.0.13
浏览器运行http://192.168.0.13/judger/pending-solutions?judger_token=token13   返回是的一个  []

**Comment by massimodong** [comment]
请在评测机服务器上执行
`wget http://localhost//judger/pending-solutions?judger_token=token13`

**Comment by 18767752565** [comment]
-oj:~$ wget http://localhost//judger/pending-solutions?judger_token=token13
--2019-02-22 11:05:28--  http://localhost//judger/pending-solutions?judger_token=token13
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-02-22 11:05:28 ERROR 404: Not Found.

**Comment by massimodong** [comment]
它不应该返回404，你可以检查一下你网站的配置。
或者把localhost改成ip地址可能能解决问题。

**Comment by 18767752565** [comment]
oj:~$ wget http://192.168.0.13//judger/pending-solutions?judger_token=token13
--2019-02-22 11:11:59--  http://192.168.0.13//judger/pending-solutions?judger_token=token13
Connecting to 192.168.0.13:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘pending-solutions?judger_token=token13’

pending-solutions?j     [ <=>                ]       2  --.-KB/s    in 0s

2019-02-22 11:11:59 (178 KB/s) - ‘pending-solutions?judger_token=token13’ saved [2]

**Comment by 18767752565** [comment]
哥们可以加个qq吗  546094038
