### ISSUE TITLE
[Bug] Whether the fields `fullname` and `class` are required is inconsistent

### ISSUE THREAD

**Issue by sjx233** [massimodong/wzoj#12]
They are required in `auth.register`:

https://github.com/massimodong/wzoj/blob/977b2545e280cca83987fb26c5d61d08a9fa4f30/resources/views/auth/register.blade.php#L22-L28

https://github.com/massimodong/wzoj/blob/977b2545e280cca83987fb26c5d61d08a9fa4f30/resources/views/auth/register.blade.php#L35-L41

But not in `user.profile`:

https://github.com/massimodong/wzoj/blob/977b2545e280cca83987fb26c5d61d08a9fa4f30/resources/views/user/profile.blade.php#L128-L133

https://github.com/massimodong/wzoj/blob/977b2545e280cca83987fb26c5d61d08a9fa4f30/resources/views/user/profile.blade.php#L146-L151

**Comment by massimodong** [comment]
This is indeed a bug. Thanks.
