### ISSUE TITLE
评测的刷新问题

### ISSUE THREAD

**Issue by kylinpoet** [massimodong/wzoj#15]
![2](https://user-images.githubusercontent.com/6766883/59653339-30366700-91c4-11e9-968f-236b474047c0.png)

一直停在  等待评测状态，刷新后正常显示。（正常情况下会有状态条）
后台 server.js 也已经运行了

顺便搭车问个问题:
评测机，评测 C++成功， python代码一直是 RE。。

**Comment by massimodong** [comment]
是以前正常现在不正常了吗？
考虑一下python版本问题？

**Comment by sjx233** [comment]
Is `SOCKET_IO_SERVER` in `.env` configured correctly? (`localhost` should be changed to where `server.js` is running)

**Comment by kylinpoet** [comment]
我用 python2 和 python3 的 print 都试过了，一直 RE....judge 加了 --debug 参数，但没有RE的错误提示输出。

（第一问：评测不能自动刷新是什么问题？server.js里需要修改什么内容吗？）

**Comment by kylinpoet** [comment]
> Is `SOCKET_IO_SERVER` in `.env` configured correctly? (`localhost` should be changed to where `server.js` is running)

May be right？ http://localhost:9000... 
I only use the defaut setting...
And then I use the IP,but the same thing happend...

**Comment by massimodong** [comment]
server.js 里面需要配置 redis 服务器，不过如果 redis 服务器在同一台电脑上且没有密码的话就不需要其他设置了。
请问你用的是什么浏览器?
浏览器加载网页后能连上 http:// ip :9000 吗？

**Comment by kylinpoet** [comment]
chrome 最新版本
redis默认本机，密码为空。基本上都是默认配置
能成功访问
多谢 耐心解答。请问下，我还能提供什么信息吗？

**Comment by massimodong** [comment]
抱歉安装指南好像有疏漏
除了 server.js 之外以下命令也需要常驻
`php artisan queue:listen --tries=3`

**Comment by kylinpoet** [comment]
多谢。已然成功。
顺便说下
apache需要开启 rewrite 和  headers 模块，安装指南里只提到了 rewrite
还有系统要安装 gd库
另外：
请问下对于 评测机 python的问题，可以怎么调试？

**Comment by massimodong** [comment]
python 交空白代码会RE吗？
(OJ对文件大小有下限，所以你可以交一个全是换行符的代码

**Comment by kylinpoet** [comment]
唉。
还是 RE。不知道问题出在哪里

**Comment by massimodong** [comment]
python RE是我评测机问题。
新版本的 python 用了两个奇怪的系统调用，现在加进去了，应该能用了。
(发现自己代码写得好丑
