### ISSUE TITLE
最近题库有一个严重的评测机Bug，内存占用显示不准确

### ISSUE THREAD

**Issue by ZeroSimple** [massimodong/wzoj#3]
所有的提交内存在不断递增。

`#include<iostream>
#include<cstdio>
using namespace std;
int main()
{
    int l,r,sum=0,q;
    cin>>l>>r;
    for(int i=l;i<=r;i++)
    {
        q=i;
        while(q>0)
        {
            if(q%10==2) sum+=1;//个位数开始判断是否含2
            q/=10;
        }
    }
    cout<<sum<<endl; 
    return 0;
}`
比如这一段代码你提交是17.17MB，过一会提交是17.19MB后来又17.25MB

PS：下次周日你来SCP教师的时候叫一句@ZeroSimple在哪里，请教你几个Git问题

**Comment by ZeroSimple** [comment]
还有前段时间提交都是1.64MB & 1.01MB，导致题目排行榜TOP3全是1.64MB & 1.01MB霸占

**Comment by ZeroSimple** [comment]
@massimodong

**Comment by ZeroSimple** [comment]
好吧，是内存占用不断增多的Bug

> 78586	Master Yip	TLE的乘幂	
评测完成
70	1996ms	17.21MB	C++	239B	LOCAL	2017-05-16 12:53:04
78585	cyz	数字统计	
评测完成
100	0ms	17.20MB	C++	228B	LOCAL	2017-05-16 12:49:47
78584	cyz	数字统计	
评测完成
编译错误	0ms	0.00MB	C++	160B	LOCAL	2017-05-16 12:49:30
78583	2528631720(南浦）	数字统计	
评测完成
100	0ms	17.20MB	C++	297B	LOCAL	2017-05-16 12:48:09
78582	Zrj1013178580	单词的长度	
评测完成
100	0ms	17.20MB	C++	250B	LOCAL	2017-05-16 12:48:07
78581	MeNG	计算曼哈顿距离	
评测完成
100	0ms	17.20MB	C++	235B	LOCAL	2017-05-16 12:47:55
78580	2528631720(南浦）	数字统计	
评测完成
10	2000ms	17.19MB	C++	371B	LOCAL	2017-05-16 12:47:17
78579	lzy大帅哥	开关灯	
评测完成
0	72ms	17.19MB	C++	285B	LOCAL	2017-05-16 12:44:11
78578	MeNG	大象喝水	
评测完成
100	0ms	17.18MB	C++	230B	LOCAL	2017-05-16 12:44:03
78577	lxz@npsy	数字统计	
评测完成
20	0ms	17.18MB	C++	223B	LOCAL	2017-05-16 12:42:10
78576	Trump	数字统计	
评测完成
100	0ms	17.18MB	C++	335B	LOCAL	2017-05-16 12:41:31
78575	MeNG	甲流疫情死亡率	
评测完成
100	0ms	17.18MB	C++	187B	LOCAL	2017-05-16 12:40:36
78574	yesyoung	数字统计	
评测完成
100	0ms	17.18MB	C++	228B	LOCAL	2017-05-16 12:39:47
78573	南浦实验的帅哥	数字统计	
评测完成
30	0ms	17.17MB	C++	255B	LOCAL	2017-05-16 12:36:59
78572	MeNG	字符菱形	
评测完成
100	0ms	17.17MB	C++	207B	LOCAL	2017-05-16 12:36:23
78571	南浦实验的帅哥	数字统计	
评测完成
10	0ms	17.17MB	C++	257B	LOCAL	2017-05-16 12:35:48
78570	cyz	数字统计	
评测完成
20	0ms	17.16MB	C++	213B	LOCAL	2017-05-16 12:35:35
78569	MeNG	数字统计	
评测完成
100	0ms	17.16MB	C++	224B	LOCAL	2017-05-16 12:32:39
78568	mia via(南浦实验)	计算浮点数相除的余数	
评测完成
100	0ms	17.15MB	C++	152B	LOCAL	2017-05-16 12:30:19
78567	mia via(南浦实验)	计算浮点数相除的余数	
评测完成
40	0ms	17.15MB	C++	134B	LOCAL	2017-05-16 12:29:32
78566	DRAGONRIDER（南浦实验）	数字统计	
评测完成
100	0ms	17.15MB	C++	261B	LOCAL	2017-05-16 12:27:42

**Comment by massimodong** [comment]
明天看看。

**Comment by massimodong** [comment]
问题解决了。
