### ISSUE TITLE
安装过程的问题

### ISSUE THREAD

**Issue by Python-PIG** [massimodong/wzoj#34]
第一，想请作者更新一下安装文档，我安装了四次了，重装了三次，还是不行，一直报错
  `  问题一
    - intervention/image[2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.3.11, 2.3.12, 2.3.13, 2.3.14, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.6.0] require ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
    - mews/captcha 2.3.0 requires intervention/image ~2.2 -> satisfiable by intervention/image[2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.3.11, 2.3.12, 2.3.13, 2.3.14, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.6.0].
    - Root composer.json requires mews/captcha 2.3.0 -> satisfiable by mews/captcha[2.3.0].`
  
    问题二：安装composer报错提示缺少php-file info依赖，但是我安装了
    
第二，我想知道作者搭建环境所使用的系统，以及各个软件的版本
（包括lamp环境对应的每一个软件的版本，还有composer的版本）

**Comment by Python-PIG** [comment]
问题一那个是报错

**Comment by Python-PIG** [comment]
点错了

**Comment by massimodong** [comment]
系统版本
Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
Apache/2.4.38 (Debian)
PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
数据库应该区别不大

**Comment by massimodong** [comment]
提示缺少 php-file info，但是你安装了，请问你启用(enable)了吗？
应该是把 php.ini 文件中的 `extension=php_fileinfo.dll` 取消注释。

**Comment by lazybainuo** [comment]
> 提示缺少 php-file info，但是你安装了，请问你启用(enable)了吗？
> 应该是把 php.ini 文件中的 `extension=php_fileinfo.dll` 取消注释，然后重启 apache2.
> 第一个报错也是缺少 php-file info 依赖导致的。

我composer用的2.x会不会是版本过高导致的？php.ini的配置我取消注释了，我换个低版本的composer试试吧
感谢回复

**Comment by Python-PIG** [comment]
感谢回复

先去试试啦

**Comment by massimodong** [comment]
是不是你php版本太低了。

**Comment by Python-PIG** [comment]
php7.4

**Comment by Python-PIG** [comment]
应该不会存在版本太低吧

**Comment by lazybainuo** [comment]
> 是不是你php版本太低了。
> 参考 https://stackoverflow.com/questions/23771117/requires-ext-fileinfo-how-do-i-add-that-into-my-composer-json-file

7.2 7.4 8.0都试过，就离谱

**Comment by massimodong** [comment]
神奇，请问你用的是什么环境啊？

**Comment by Python-PIG** [comment]
centos，Ubuntu都试过，现在用debian试试

**Comment by Python-PIG** [comment]
还有我其实很好奇，请问您是温州中学的老师吗？感觉你不像是舒春平老师哈哈哈

**Comment by lazybainuo** [comment]
> 神奇，请问你用的是什么环境啊？

目前是debian10发行版+标准lamp，我刚刚又去试了一下，fileinfo报错的原因是宝塔安装拓展是直接编译进php，然后配置文件还被注释了，然后宝塔默认的composer都是2.x
这是composer报错
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> post-autoload-dump: UpdateHelper\ComposerPlugin->onAutoloadDump
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    Please consider upgrading your Laravel dependencies to be compatible with Carbon 2:
      - laravel/framework at least to version 5.8.0

    If you can't update Laravel, check https://carbon.nesbot.com/ to see how to
    install Carbon 2 using alias version and our adapter kylekatarnls/laravel-carbon-2

    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
15 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> post-update-cmd: Illuminate\Foundation\ComposerScripts::postUpdate
> post-update-cmd: php artisan optimize
Executing command (CWD): php artisan optimize
Generating optimized class loader

                                                                                           
  [Symfony\Component\Process\Exception\RuntimeException]                                   
  The Process class relies on proc_open, which is not available on your PHP installation.  
                                                                                           

Script php artisan optimize handling the post-update-cmd event returned with error code 1

**Comment by lazybainuo** [comment]
我现在正在手动搭建lamp环境，不用宝塔的了，宝塔太坑人了

**Comment by lazybainuo** [comment]
导入数据库出错，请问原因
Migration table created successfully.
                                                                                
  [Doctrine\DBAL\Exception]                                                                                   
  An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `N  
  ull`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACT  
  ER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEM  
  A = 'wzoj' AND TABLE_NAME = 'users' ORDER BY ORDINAL_POSITION ASC':                                         
                                                                                                              
  Argument 1 passed to Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement() must be an instance o  
  f Doctrine\DBAL\Driver\ResultStatement, instance of PDOStatement given, called in /home/www/wzoj/vendor/do  
  ctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1312                                                   
                                                                                                              

                                                                                                              
  [TypeError]                                                                                                 
  Argument 1 passed to Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement() must be an instance o  
  f Doctrine\DBAL\Driver\ResultStatement, instance of PDOStatement given, called in /home/www/wzoj/vendor/do  
  ctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1312

**Comment by lazybainuo** [comment]
> 导入数据库出错，请问原因
> Migration table created successfully.
> 
> [Doctrine\DBAL\Exception]
> An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `N ull`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACT
> ER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEM
> A = 'wzoj' AND TABLE_NAME = 'users' ORDER BY ORDINAL_POSITION ASC':
> 
> Argument 1 passed to Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement() must be an instance o
> f Doctrine\DBAL\Driver\ResultStatement, instance of PDOStatement given, called in /home/www/wzoj/vendor/do
> ctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1312
> 
> [TypeError]
> Argument 1 passed to Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement() must be an instance o
> f Doctrine\DBAL\Driver\ResultStatement, instance of PDOStatement given, called in /home/www/wzoj/vendor/do
> ctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1312

我目前环境Debian+php7.3+apache2.4+mariadb10安装composer的时候基本上都没问题了就这个数据库报错

**Comment by Python-PIG** [comment]
@massimodo

**Comment by Python-PIG** [comment]
为了方便的实时交流，可以加一下qq吗。GitHub有一点不方便。

**Comment by Python-PIG** [comment]
@massimodong

**Comment by massimodong** [comment]
没见过这个错误... 请问你的数据库里现在有什么了？

**Comment by Python-PIG** [comment]
`show tables;
+---------------------+
| Tables_in_wzoj      |
+---------------------+
| answerfiles         |
| diy_pages           |
| failed_jobs         |
| files               |
| forum_replies       |
| forum_tags          |
| forum_topics        |
| group_invitation    |
| group_problemset    |
| group_user          |
| groups              |
| homeworks           |
| invitations         |
| judgers             |
| migrations          |
| options             |
| password_resets     |
| problem_problem_tag |
| problem_problemset  |
| problem_tags        |
| problems            |
| problemsets         |
| role_user           |
| roles               |
| sessions            |
| side_panels         |
| sidebars            |
| sims                |
| solutions           |
| users               |
+---------------------+
30 rows in set (0.000 sec)

MariaDB [wzoj]> `

**Comment by lazybainuo** [comment]
> 没见过这个错误... 请问你的数据库里现在有什么了？

大佬方便添加一下好友吗，tg或者qq或者微信钉钉都可以

**Comment by Python-PIG** [comment]
数据表好像都有了，但是后面导入的东西好像报错

**Comment by massimodong** [comment]
我github主页应该有我联系方式，或者你留一下你的联系方式？
大概是初始化数据库哪一部出错了吧...

**Comment by lazybainuo** [comment]
> 我github主页应该有我联系方式，或者你留一下你的联系方式？
> 大概是初始化数据库哪一部出错了吧...

我的QQ是2320873696
微信bainuo8886665
邮箱bainuo233@foxmail.com刚刚已经给你发邮件了

**Comment by massimodong** [comment]
依赖 Doctrine\DBAL 新版本出问题了。安装的时候请不要执行 composer update 改变现有的依赖库的版本。
