### ISSUE TITLE
你好，请问下有安装和使用说明吗？

### ISSUE THREAD

**Issue by kylinpoet** [massimodong/wzoj#5]
我想在本地搭建一个平台，不知道如何进行。

**Comment by massimodong** [comment]
在wiki有。不过可能不是很全。。
https://github.com/massimodong/wzoj/wiki/安装指南。。
安装有困难的话直接回复我谢谢。

评测机的安装方式稍后补上。

**Comment by 18767752565** [comment]
如何安装 ，看不懂啊，有详细的教程吗？

**Comment by 18767752565** [comment]
比如怎么安装 安装redis缓存系统
 VirtualHost配置中增加   具体怎么增加
怎么开启mod_rewrite模块
怎么安装composer库    都不会啊   求详细教程

**Comment by massimodong** [comment]
你先照着我给的链接一步一步来?
哪里写得不清楚请再告诉我,谢谢.

**Comment by massimodong** [comment]
redis是独立于本项目的一个缓存服务,安装方法..
因操作系统而异?
您可以试试搜索引擎.

**Comment by massimodong** [comment]
至于apache或者nginx,两个选一个就好了.
你可以先试着搭建一个wordpress博客系统什么的,大概就理解它们是干什么的了.

**Comment by massimodong** [comment]
composer也是一个第三方软件,
它的官网(貌似)有比较详细的安装方法.

**Comment by 18767752565** [comment]
好的  感谢  先试一下  有问题  再来请教哦

**Comment by 18767752565** [comment]
你好，再问一下，wzoj-judger和wzoj应该分别是判题机和web端    要先安装哪个呀

**Comment by 18767752565** [comment]
哥，你好，VirtualHost配置中增加        是在哪个文件中增加啊
怎么开启mod_rewrite模块？

**Comment by massimodong** [comment]
judger是评测机
wzoj是web端

请问你的操作系统是?

**Comment by 18767752565** [comment]
Ubuntu

**Comment by massimodong** [comment]
https://askubuntu.com/questions/48362/how-to-enable-mod-rewrite-in-apache

2018年1月11日 08:31，"18767752565" <notifications@github.com>写道：

**Comment by 18767752565** [comment]
为什么执行php artisan migrate   出现这样的错误
PHP Warning:  require(/home/www/wzoj/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/www/wzoj/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/www/wzoj/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/www/wzoj/bootstrap/autoload.php on line 17

**Comment by massimodong** [comment]
先执行 composer install 下载必要的文件

**Comment by 18767752565** [comment]
哦  再运行了一次composer install可以了，还有个问题
通过'Default'通道注册一个普通账户    是怎么操作啊？

**Comment by massimodong** [comment]
所谓Default注册通道就是刚安装好之后默认注册方式，就是普通地注册一个用户。
默认主页是public文件夹，其他的都是不能公开的。

**Comment by 18767752565** [comment]
我用oj -> /var/www/wzoj/public    链接到public   放到:/var/www/html这个目录下    打不开  出现下面这个错误   为什么呢

192.168.0.13 目前无法处理此请求。
HTTP ERROR 500

**Comment by massimodong** [comment]
只是把public链接过去？ 当然不能这样做啊。。。
你要移也是把整个wzoj目录移过去。

**Comment by 18767752565** [comment]
整个移过去了   192.168.0.103 - - [11/Jan/2018:16:35:26 +0800] "GET /oj/public/index.php HTTP/1.1" 500 185 "-" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)"

**Comment by massimodong** [comment]
/var/log/apache2/error.log
这里面一般会有500的原因。

**Comment by 18767752565** [comment]
/var/log/apache2/error.log这里是这样的
[Thu Jan 11 16:35:26.333844 2018] [:error] [pid 25148] [client 192.168.0.103:49226] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/wzoj/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/wzoj/bootstrap/cache/compiled.php:13434\nStack trace:\n#0 /var/www/wzoj/bootstrap/cache/compiled.php(13364): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/wzoj/bootstrap/cache/compiled.php(13124): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/wzoj/bootstrap/cache/compiled.php(13222): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#3 /var/www/wzoj/bootstrap/cache/compiled.php(12917): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/wzoj/bootstrap/cache/compiled.php(12888): Illuminate\\Log\\Writer->writeLog('error', Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 /var/www/wzoj/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(50): Illuminate\\Log\\Writer->error(Ob in /var/www/wzoj/bootstrap/cache/compiled.php on line 13434

**Comment by massimodong** [comment]
啊，我的锅。
理论上至少要给storage和bootstrap/cache两个文件夹开写权限。
不过因为网页要自己更新自己，所以最好给整个目录写权限。

`chown -R www-data.www-data /home/www/wzoj`

**Comment by 18767752565** [comment]
给了权限了，已经可以正常访问了，但是界面是乱的   图片显示不出来，为什么呢

**Comment by 18767752565** [comment]
点击注册   就跳转到http://192.168.0.13/auth/register，路径不对   我已经把整个wzoj都搬到/var/www/html

**Comment by massimodong** [comment]
首先,你给的是内网地址.我访问不了 
其次,oj要求把根路径放在/wzoj/public
即http//192.168.0.13/就是oj主页,不然上级文件就暴露出来了

**Comment by 18767752565** [comment]
哦   把主页改到/wzoj/public  这里就正常了。但是访问注册页面  http://192.168.0.13/auth/register
就找不到页面了，我看了wzoj/public/下并没有auth目录  ？

**Comment by massimodong** [comment]
请开启mod_rewrite模块
并检查apache配置文件

**Comment by 18767752565** [comment]
sudo a2enmod rewrite就提示
Module rewrite already enabled
应该是已经开启了mod_rewrite了吧，apache配置文件，是这个吗 /etc/apache2/apache2.conf   检查哪个位置呀

**Comment by massimodong** [comment]
改完了,包括a2enmod命令之后,要重启apache的
配置文件对应这个网站的配置文件

**Comment by 18767752565** [comment]
sudo /etc/init.d/apache2 restart这样重启了   还是一样
配置文件对应这个网站的配置文件     是什么意思啊   可以具体点吗   新手有点搞不懂

**Comment by massimodong** [comment]
emmm..
你是不是略过了安装指南的 apache服务器配置 那一部分
就是那个配置文件

**Comment by 18767752565** [comment]
没略过呢，后来我看到你那里很详细的  我照做了
在/etc/apache2/sites-enabled/目录新建文件，wzoj.conf
然后把下面这段复制进去
<VirtualHost *:80>
        ServerAdmin youremail@em.com
        DocumentRoot /home/www/wzoj/public
        ##ServerName servername.com

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        <Directory "/home/www/wzoj/public">
                Options Indexes FollowSymLinks ExecCGI Includes
                AllowOverride All
                Require all granted
        </Directory>
</VirtualHost>
然后用sudo a2enmod rewrite开启mod_rewrite模块。
重启apache服务器

wzoj.conf这个文件是新建了   是不是要和系统联系起来？系统有调用这个文件吗

**Comment by massimodong** [comment]
你可以先了解一下apache具体是什么,以及ubuntu下配置文件的问题,我可能说不明白.

这时候,我猜测,要把sites_enabled里面其他的文件都删掉,然后重启服务器.
当然要先把这个配置文件里面的两个目录改对.

**Comment by 18767752565** [comment]
DocumentRoot /home/www/wzoj/public
<Directory "/home/www/wzoj/public">
这两个路径我没写对，我是放在/var/www/wzoj
但是改过来也还依然不行    这两个路径要相同的吗   分别是代表什么意思？

**Comment by 18767752565** [comment]
哥，我刚刚又重装了Ubuntu16，按照步骤重新走了一遍，还是那个问题，点“”注册“”http://192.168.0.13/auth/register这个页面就打不开
出现错误：
Not Found
The requested URL /auth/register was not found on this server
求救

**Comment by 18767752565** [comment]
网站根目录在wzoj/public
然后注册的时候要访问的目录在wzoj/resources/views/auth
是不是有问题啊

**Comment by massimodong** [comment]
000-default.conf 和 wzoj.conf 重复了.
删掉一个.
参考我上个回答

**Comment by 18767752565** [comment]
我安装好了，是环境的问题，谢谢耐心指导哈
注册的时候验证码为什么没显示，就是captcha，是权限问题吗
然后点注册就出错了MissingDependencyException in ImageManager.php line 133:

**Comment by massimodong** [comment]
请问你是把你的某些回复删除了吗？
为什么我收到了邮件提醒却在这里看不到。。
github鬼畜了？

**Comment by 18767752565** [comment]
嗯嗯  是我删除了，我web端已经安装好了   谢谢耐心指导  
系统有没有使用说明啊

**Comment by 18767752565** [comment]
可以加一下qq或者微信吗我的qq546094038   或者留个邮箱也行，万谢
