### ISSUE TITLE
系统使用问题

### ISSUE THREAD

**Issue by 18767752565** [massimodong/wzoj#6]
我把系统放在内网，想通过端口映射的方法在外网访问
但是映射了之后，提示无法访问：
此站点无法访问！
可能原因：
您没有将此域名或IP绑定到对应站点!
配置文件未生效!

是不是要改配置呀？

还有新建的比赛，如何隐藏啊？把“公开”去掉，叶还显示在首页

**Comment by massimodong** [comment]
1. 不知道，请联系你们网管。。。
2. 请用非管理员帐号看看是否还在首页。

**Comment by 18767752565** [comment]
如果是比赛，即apoi、acm、oi这三种   把“公开”去掉，也还显示在首页。后来把它改成题目集合，而且“公开”不勾选，就可以隐藏了。是这样的吗   比赛不可以隐藏？
还有这里面的三种比赛类型在功能上有区别吗？求解答，谢谢哈

**Comment by 18767752565** [comment]
同一个系统再新建一个普通站点，把映射改一下就可以在外网访问，但是映射到wzoj的地址和端口  就访问不了，所以我在想系统里面是不是有哪里有设置本机ip什么的

**Comment by massimodong** [comment]
你碰到的问题绝大概率和oj无关
oj假定自己在最顶层目录(如不能在 http://www.example.com/sub/)
但是和其他应该没有关系.

**Comment by 18767752565** [comment]
好的好的  谢谢哈
顺便再问一下，有没有一种模式是学生提交了代码，错误  能显示他的答案

**Comment by massimodong** [comment]
不懂..什么叫显示答案?

**Comment by 18767752565** [comment]
哦  好的  那就是没有   谢谢O(∩_∩)O~

**Comment by 18767752565** [comment]
再问一个问题哈，用户如果密码忘记了，如何重置用户密码啊，谢谢

**Comment by massimodong** [comment]
设置好.env里面的邮件发送相关设置
就可以用找回密码功能了

**Comment by 18767752565** [comment]
哦，好的，那用户的邮箱管理员可以帮忙改吗

**Comment by massimodong** [comment]
不可以
但是可以进数据库改

**Comment by 18767752565** [comment]
哦，好的，谢谢哈
系统有数据导入功能，但是好像没有导出功能？

**Comment by massimodong** [comment]
是的
目前支持从hustoj导入题目
导出功能打算各部分完善后再写.

**Comment by 18767752565** [comment]
好的好的，明白了，谢谢

**Comment by 18767752565** [comment]
你好，再问一个问题，题目的题解，用户要怎么才能看到啊？还是说只有管理员才能看到？

**Comment by massimodong** [comment]
用户能访问题目
或者比赛结束.

**Comment by 18767752565** [comment]
哦  好的  谢谢
