### ISSUE TITLE
系统更新问题

### ISSUE THREAD

**Issue by 18767752565** [massimodong/wzoj#7]
哥，系统可以更新吗，在系统里面更新出现错误，是不是需要哪里操作一下啊

Start updating...
Getting latest release:v1.8
Downloading..
Enabling Maintenance Mode
    
                
Whoops, looks like something went wrong.

ErrorException in AdminUpdateSystemController.php line 79:

                            
system() has been disabled for security reasons

**Comment by massimodong** [comment]
如您所贴.
system() has been disabled for security reasons
手动更新吧.

**Comment by 18767752565** [comment]
哦  好的  谢谢
